In [2]:
from sentence_transformers import SentenceTransformer

In [3]:
model_name = 'sentence-transformers/all-MiniLM-L6-v2'

model = SentenceTransformer(model_name)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
model

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [5]:
sentence1 = 'I love you.'
sentence2 = 'I like you.'
sentence3 = 'I hate you.'

In [12]:
result1 = model.encode(sentence1)
result2 = model.encode(sentence2)
result3 = model.encode(sentence3)

In [14]:
from sentence_transformers import util

# Calculate cosine similarity matrix for all three sentences
similarities = util.cos_sim([result1, result2, result3], [result1, result2, result3])

print("Similarity matrix:\n", similarities)


Similarity matrix:
 tensor([[1.0000, 0.6839, 0.5852],
        [0.6839, 1.0000, 0.6604],
        [0.5852, 0.6604, 1.0000]])


/usr/local/lib/python3.12/dist-packages/sentence_transformers/util/tensor.py:28: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:253.)
  a = torch.tensor(a)


In [15]:
sentence = "I love football"

embedding = model.encode(sentence)

print(type(embedding))
print(embedding.shape)
print(embedding[:10])

<class 'numpy.ndarray'>
(384,)
[-0.00767933 -0.01246621 -0.01382193 -0.07702471  0.07841557  0.01013702
  0.08043254  0.06242574  0.09999694  0.05245049]


In [16]:
import numpy as np

# Similarity between 'I love you' and 'I like you'
sim_1_2 = np.dot(result1, result2)

# Convert similarity to Cosine Distance (0 means identical, 2 means opposites)
dist_1_2 = 1 - sim_1_2

print(f"Cosine Distance: {dist_1_2}")


Cosine Distance: 0.31613707542419434


In [17]:
import numpy as np

# Similarity between 'I love you' and 'I like you'
sim_1_3 = np.dot(result1, result3)

# Convert similarity to Cosine Distance (0 means identical, 2 means opposites)
dist_1_3 = 1 - sim_1_3

print(f"Cosine Distance: {dist_1_3}")


Cosine Distance: 0.41477566957473755


In [8]:
import torch

def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

1. **Semantic Search**
2. **RAG**
3. **Recommendation**
4. **Clustering**



> **Embedding:** It shows the similarity to another `text`.



In [28]:
sentences = [
    "I love football.",
    "I enjoy soccer.",
    "Python is a programming language.",
    "Artificial intelligence is transforming the world.",
    "Cats are cute animals.",
    'Lion is the animal'
]

In [29]:
embeddings = model.encode(sentences)

In [30]:
embeddings.shape

(6, 384)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(embeddings)

print(similarity)

[[0.99999994 0.7673867  0.05710349 0.15304615 0.24520536 0.21587975]
 [0.7673867  1.         0.14331713 0.16314998 0.19957529 0.16869251]
 [0.05710349 0.14331713 1.         0.2678437  0.1756587  0.16520175]
 [0.15304615 0.16314998 0.2678437  0.9999999  0.08298128 0.13257954]
 [0.24520536 0.19957529 0.1756587  0.08298128 0.9999999  0.4636713 ]
 [0.21587975 0.16869251 0.16520175 0.13257954 0.4636713  0.9999999 ]]


In [32]:
documents = [
    "Python is a popular programming language.",
    "Football is the world's most popular sport.",
    "Artificial intelligence is changing many industries.",
    "Cats are friendly domestic animals.",
    "Machine learning is a subset of artificial intelligence.",
    "Messi is one of the greatest football players.",
    "Pandas is a Python library for data analysis."
]

In [33]:
document_embeddings = model.encode(documents)

### Bu odatda bir marta qilinadi va Vector DB (FAISS, Chroma va boshqalar)ga saqlanadi.

In [34]:
query = "How can I learn Python?"

In [35]:
query_embedding = model.encode(query)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

scores = cosine_similarity(
    [query_embedding],
    document_embeddings
)[0]

In [38]:
scores

array([ 0.66494536, -0.01232216,  0.08717045,  0.11058724,  0.13009752,
       -0.03922553,  0.39936918], dtype=float32)

In [39]:
import numpy as np

top_k = 3

top_indices = np.argsort(scores)[::-1][:top_k]

print(query)
print("-" * 40)

for idx in top_indices:
    print(f"Score: {scores[idx]:.4f}")
    print(documents[idx])
    print("-" * 40)

How can I learn Python?
----------------------------------------
Score: 0.6649
Python is a popular programming language.
----------------------------------------
Score: 0.3994
Pandas is a Python library for data analysis.
----------------------------------------
Score: 0.1301
Machine learning is a subset of artificial intelligence.
----------------------------------------


### **The base of RAG system**
```
Documents
      ↓
Document Embeddings
      ↓
User Question
      ↓
Question Embedding
      ↓
Cosine Similarity
      ↓
Top-3 Documents
```